#write a playbook to create a file in all host nodes
---
- name: Create a file
  hosts: all
  tasks:
    - name: Create file
      become: true
      file:
        path: /path/to/file.txt
        state: touch
